import torch
import torch.nn as nn

class NNModel:
    """
    A Feedforward Neural Network for binary health outcome prediction.
    
    This model ingests the 12 features generated by the UserInput Pydantic model 
    and outputs raw logits. It utilizes dropout for regularization to prevent 
    overfitting on tabular demographic/health data.
    """
    def __init__(self, input_dim: int = 12, hidden_1: int = 24, 
                 hidden_2: int = 16, dropout_rate: float = 0.2):
        """
        Initializes the neural network layers.
        
        Args:
            input_dim (int): Number of input features (default: 12).
            hidden_1 (int): Size of the first hidden layer.
            hidden_2 (int): Size of the second hidden layer.
            dropout_rate (float): Probability of an element to be zeroed.
        """
        
        super().__init__()
        
        self.model = nn.Sequential(
            nn.Linear(input_dim, hidden_1),  
            nn.ReLU(),
            nn.Dropout(dropout_rate),
            nn.Linear(hidden_1, hidden_2),
            nn.ReLU(),
            nn.Dropout(dropout_rate),
            nn.Linear(hidden_2, 1) 
        )

        self.loss_fn   = nn.BCEWithLogitsLoss()
        self.optimizer = torch.optim.Adam(self.model.parameters(), lr=0.001)

    def get_model(self):
         return self.model

    def get_optimizer(self):
        return self.optimizer
        
    def get_loss_fn(self):
        return self.loss_fn
